name: Generic CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests
      run: |
        echo "Add your test commands here"
        # Example:
        # - make test
        # - ./run-tests.sh
        # - custom-test-command
